import type { PathComponent, PathResult, ProfileResult, Vec3 } from '../types';
import { fmt } from './emitBosl2';

const HEADER = `// Generated by Roseriser — DXF to OpenSCAD swept solid (prism emitter)
//
// This emitter does NOT require BOSL2 and does NOT interpolate the profile
// orientation between adjacent vertices. Each discretised path segment
// becomes a single linear_extrude() prism whose cross-section is the
// profile polygon, oriented with its +Y axis pointing at world +Z (up).
// All prisms are combined with union().
//
// This is the cleanest choice for Gothic tracery built from straight runs
// joined at sharp corners: every segment is a perfect prism, every
// intersection resolves to a clean union. Outer corners whose angle is less
// than ~90° will show a small missing wedge where two prism end-caps meet;
// for those, use the hull emitter instead.`;

export function emitPrism(profile: ProfileResult, path: PathResult): string {
  const poly = profile.vertices
    .map((v) => `  [${fmt(v[0])}, ${fmt(v[1])}]`)
    .join(',\n');

  const comps = path.components.length > 0 ? path.components : [
    { points: path.points, closed: path.closed, length: path.length }
  ];

  const segmentLists = comps
    .map((c, i) => {
      const segs = extractSegments(c);
      const body = segs
        .map(
          ([a, b]) =>
            `  [[${fmt(a[0])}, ${fmt(a[1])}, ${fmt(a[2])}], [${fmt(b[0])}, ${fmt(b[1])}, ${fmt(b[2])}]]`
        )
        .join(',\n');
      return `segments_${i + 1} = [\n${body}\n];`;
    })
    .join('\n\n');

  const calls = comps
    .map((_, i) => `  for (s = segments_${i + 1}) segment_prism(s);`)
    .join('\n');

  return `${HEADER}

polygon_points = [
${poly}
];

${segmentLists}

module segment_prism(seg) {
  delta = seg[1] - seg[0];
  L = norm(delta);
  // atan2 in OpenSCAD returns degrees, which is what rotate() expects.
  angle = atan2(delta[1], delta[0]);
  if (L > 1e-9)
    translate(seg[0])
      rotate([0, 0, angle + 90])
        rotate([90, 0, 0])
          linear_extrude(height = L)
            polygon(polygon_points);
}

union() {
${calls}
}
`;
}

function extractSegments(c: PathComponent): [Vec3, Vec3][] {
  const segs: [Vec3, Vec3][] = [];
  for (let i = 0; i + 1 < c.points.length; i++) {
    segs.push([c.points[i], c.points[i + 1]]);
  }
  if (c.closed && c.points.length > 1) {
    segs.push([c.points[c.points.length - 1], c.points[0]]);
  }
  return segs;
}
