import type { PathComponent, PathResult, ProfileResult, Vec2, Vec3 } from '../types';
import { fmt } from './emitBosl2';

export interface HullEmitOptions {
  /** Optional remover profile subtracted via difference(). */
  remover?: ProfileResult;
}

/**
 * Vertices whose incoming and outgoing tangents differ by more than this many
 * degrees are treated as "sharp corners": the beam on each side is made a
 * clean prism (using that segment's own tangent at the shared vertex), and a
 * small hull-miter filler is emitted at the vertex itself. Below this
 * threshold the vertex is "smooth" — we use the averaged-direction tangent,
 * which interpolates nicely along discretised arcs.
 */
const SHARP_CORNER_THRESHOLD_DEG = 15;

const HEADER = `// Generated by Roseriser — DXF to OpenSCAD swept solid (hull fallback)
//
// This emitter does NOT require BOSL2. Each path is turned into a list of
// "beams" (hull of two profile slabs at adjacent vertices) and a list of
// "miters" (hull of two profile slabs at the same vertex, one perpendicular
// to the incoming tangent and one to the outgoing). Beams run with a single
// tangent at each endpoint so that straight runs stay perfectly prismatic;
// smooth arcs keep their hull interpolation because the tangent change per
// vertex is below the sharp-corner threshold.
//
// Orientation convention (matches the BOSL2 emitter's normal=[0,0,1]):
//   profile local +Y → world +Z  (profile stands upright)
//   profile local +X → 90° CCW from tangent in the XY plane (horizontal)
//
// All components are union()'d. Crossing paths (e.g. Gothic tracery) just
// fall out of union naturally.`;

export function emitHull(profile: ProfileResult, path: PathResult, opts: HullEmitOptions = {}): string {
  const poly = vertsToScad(profile.vertices);
  const remPoly = opts.remover ? vertsToScad(opts.remover.vertices) : null;

  const comps = path.components.length > 0 ? path.components : [
    { points: path.points, closed: path.closed, length: path.length }
  ];
  const multi = comps.length > 1;

  const parts = comps.map((c, idx) => renderComponent(c, idx, multi));
  const vars = parts.map((p) => p.vars).join('\n\n');
  const modules = parts.map((p) => p.module).join('\n\n');

  // Orientation convention documented in the header. +Y of the profile ends up
  // along world +Z after rotations, so a "tall" profile stands upright.
  const profAtModule = `module prof_at(p, ang, poly) {
  translate(p)
    rotate([0, 0, ang + 90])
      rotate([90, 0, 0])
        linear_extrude(height = 0.001, center = true)
          polygon(poly);
}`;

  const sweepBody = (polyVar: string): string => {
    const perComp = parts.map((p) => `sweep${p.suffix}(${polyVar});`);
    if (multi) return `union() {\n${perComp.map((c) => `  ${c}`).join('\n')}\n}`;
    return perComp[0];
  };

  if (remPoly !== null) {
    return `${HEADER}

polygon_points = [
${poly}
];

remover_polygon = [
${remPoly}
];

${vars}

${profAtModule}

${modules}

difference() {
  ${sweepBody('polygon_points').split('\n').join('\n  ')}
  ${sweepBody('remover_polygon').split('\n').join('\n  ')}
}
`;
  }

  return `${HEADER}

polygon_points = [
${poly}
];

${vars}

${profAtModule}

${modules}

${sweepBody('polygon_points')}
`;
}

function vertsToScad(verts: readonly Vec2[]): string {
  return verts.map((v) => `  [${fmt(v[0])}, ${fmt(v[1])}]`).join(',\n');
}

interface ComponentBlock {
  vars: string;
  module: string;
  call: string;
  suffix: string;
}

interface Beam {
  startIdx: number;
  endIdx: number;
  startAng: number;
  endAng: number;
}

interface Miter {
  vertexIdx: number;
  inAng: number;
  outAng: number;
}

function renderComponent(c: PathComponent, idx: number, multi: boolean): ComponentBlock {
  const suffix = multi ? `_${idx + 1}` : '';
  const { beams, miters } = analyseComponent(c, SHARP_CORNER_THRESHOLD_DEG);

  const pts = c.points
    .map((p) => `  [${fmt(p[0])}, ${fmt(p[1])}, ${fmt(p[2])}]`)
    .join(',\n');

  const beamsBody = beams.length > 0
    ? beams
        .map(
          (b) =>
            `  [${b.startIdx}, ${b.endIdx}, ${fmt(b.startAng)}, ${fmt(b.endAng)}]`
        )
        .join(',\n')
    : '';
  const mitersBody = miters.length > 0
    ? miters
        .map((m) => `  [${m.vertexIdx}, ${fmt(m.inAng)}, ${fmt(m.outAng)}]`)
        .join(',\n')
    : '';

  const vars = `path_points${suffix} = [
${pts}
];

// Beams: [start_idx, end_idx, start_tangent_deg, end_tangent_deg]
beams${suffix} = [${beamsBody ? `\n${beamsBody}\n` : ''}];

// Miter fillers at sharp corners: [vertex_idx, incoming_tangent_deg, outgoing_tangent_deg]
miters${suffix} = [${mitersBody ? `\n${mitersBody}\n` : ''}];`;

  const mod = `module sweep${suffix}(poly) {
  for (b = beams${suffix}) {
    hull() {
      prof_at(path_points${suffix}[b[0]], b[2], poly);
      prof_at(path_points${suffix}[b[1]], b[3], poly);
    }
  }
  for (m = miters${suffix}) {
    hull() {
      prof_at(path_points${suffix}[m[0]], m[1], poly);
      prof_at(path_points${suffix}[m[0]], m[2], poly);
    }
  }
}`;

  return { vars, module: mod, call: `sweep${suffix}();`, suffix };
}

function analyseComponent(
  c: PathComponent,
  thresholdDeg: number
): { beams: Beam[]; miters: Miter[] } {
  const pts = c.points;
  const n = pts.length;
  if (n < 2) return { beams: [], miters: [] };

  const segCount = c.closed ? n : n - 1;
  const segTans: number[] = [];
  for (let i = 0; i < segCount; i++) {
    const j = (i + 1) % n;
    segTans.push(angleDeg(pts[j][0] - pts[i][0], pts[j][1] - pts[i][1]));
  }

  const vdata = pts.map((_, i) => {
    let inAng: number;
    let outAng: number;
    if (c.closed) {
      inAng = segTans[(i - 1 + n) % n];
      outAng = segTans[i];
    } else {
      // Open-path endpoints have only one neighbour segment. Mirror it so the
      // vertex reads as "smooth" and we never classify an endpoint as sharp.
      inAng = i > 0 ? segTans[i - 1] : segTans[0];
      outAng = i < n - 1 ? segTans[i] : segTans[n - 2];
    }
    const delta = Math.abs(normAngleDelta(outAng - inAng));
    const endpointOfOpen = !c.closed && (i === 0 || i === n - 1);
    const isSharp = !endpointOfOpen && delta > thresholdDeg;
    const avgAng = averageAngle(inAng, outAng);
    return { inAng, outAng, avgAng, isSharp };
  });

  const beams: Beam[] = [];
  for (let i = 0; i < segCount; i++) {
    const j = (i + 1) % n;
    const startAng = vdata[i].isSharp ? vdata[i].outAng : vdata[i].avgAng;
    const endAng = vdata[j].isSharp ? vdata[j].inAng : vdata[j].avgAng;
    beams.push({ startIdx: i, endIdx: j, startAng, endAng });
  }

  const miters: Miter[] = [];
  vdata.forEach((v, i) => {
    if (v.isSharp) miters.push({ vertexIdx: i, inAng: v.inAng, outAng: v.outAng });
  });

  return { beams, miters };
}

function angleDeg(dx: number, dy: number): number {
  return (Math.atan2(dy, dx) * 180) / Math.PI;
}

function normAngleDelta(d: number): number {
  // Normalise to (-180, 180].
  return (((d + 180) % 360) + 360) % 360 - 180;
}

function averageAngle(a: number, b: number): number {
  const ar = (a * Math.PI) / 180;
  const br = (b * Math.PI) / 180;
  return (Math.atan2(Math.sin(ar) + Math.sin(br), Math.cos(ar) + Math.cos(br)) * 180) / Math.PI;
}

/**
 * Per-vertex tangent in degrees, wrapped for closed paths.
 * Kept exported because callers outside the emitter rely on it.
 */
export function computeTangentsDeg(points: readonly Vec3[], closed: boolean): number[] {
  const n = points.length;
  const result: number[] = [];
  for (let i = 0; i < n; i++) {
    let prevIdx = i - 1;
    let nextIdx = i + 1;
    if (closed) {
      prevIdx = (prevIdx + n) % n;
      nextIdx = nextIdx % n;
    } else {
      if (prevIdx < 0) prevIdx = i;
      if (nextIdx >= n) nextIdx = i;
    }
    const dx = points[nextIdx][0] - points[prevIdx][0];
    const dy = points[nextIdx][1] - points[prevIdx][1];
    result.push(angleDeg(dx, dy));
  }
  return result;
}
