import type { PathResult, ProfileResult } from '../types';

export interface BosLEmitOptions {
  /** Filename stem used in the header comment. */
  name?: string;
}

const HEADER = `// Generated by Roseriser — DXF to OpenSCAD swept solid
//
// This file requires the BOSL2 library:
//   https://github.com/BelfrySCAD/BOSL2
//
// Install:
//   1. Download the ZIP from the URL above (or git clone the repo).
//   2. Move the extracted folder, renamed to "BOSL2", into your OpenSCAD
//      libraries folder:
//        Linux / macOS:  ~/.local/share/OpenSCAD/libraries/BOSL2
//        Windows:        %USERPROFILE%\\Documents\\OpenSCAD\\libraries\\BOSL2
//   3. Restart OpenSCAD.
//
// path_sweep() keeps the profile orthogonal to the path tangent by default,
// which is what tracery sweeps want.`;

export function emitBosl2(profile: ProfileResult, path: PathResult, opts: BosLEmitOptions = {}): string {
  const name = opts.name ?? 'sweep';
  const poly = profile.vertices
    .map((v) => `  [${fmt(v[0])}, ${fmt(v[1])}]`)
    .join(',\n');

  const comps = path.components.length > 0 ? path.components : [
    { points: path.points, closed: path.closed, length: path.length }
  ];
  const multi = comps.length > 1;
  const totalLength = comps.reduce((s, c) => s + c.length, 0);

  const pathLiterals = comps
    .map((c, i) => {
      const suffix = multi ? `_${i + 1}` : '';
      const body = c.points
        .map((p) => `  [${fmt(p[0])}, ${fmt(p[1])}, ${fmt(p[2])}]`)
        .join(',\n');
      return `path_points${suffix} = [\n${body}\n];`;
    })
    .join('\n\n');

  // `normal=[0,0,1]` pins the profile's local Y-axis to world-Z so the sweep
  // stays upright instead of twisting at sharp corners. Correct for any
  // planar (z=0) tracery path.
  const calls = comps.map((c, i) => {
    const suffix = multi ? `_${i + 1}` : '';
    const indent = multi ? '  ' : '';
    return `${indent}path_sweep(polygon_points, path_points${suffix}, closed=${c.closed ? 'true' : 'false'}, normal=[0,0,1]);`;
  });
  const body = multi ? `union() {\n${calls.join('\n')}\n}` : calls[0];

  const topology = comps.map((c) => (c.closed ? 'closed' : 'open')).join(', ');
  const pathMeta = [
    `// Source: ${name}`,
    `// Path entities: ${path.entityCount}`,
    `// Path components: ${comps.length} (${topology})`,
    `// Total path length: ${fmt(totalLength)}`,
    `// Profile vertices: ${profile.vertices.length}`
  ].join('\n');

  return `${HEADER}

${pathMeta}

include <BOSL2/std.scad>

polygon_points = [
${poly}
];

${pathLiterals}

${body}
`;
}

/** Fixed 6-decimal formatter that collapses -0 to 0 and trims trailing zeros. */
export function fmt(n: number): string {
  if (!Number.isFinite(n)) return '0';
  const normalised = Object.is(n, -0) ? 0 : n;
  const fixed = normalised.toFixed(6);
  // Strip trailing zeros after the decimal but keep at least one digit.
  return fixed.replace(/(\.\d*?)0+$/, '$1').replace(/\.$/, '');
}
